on:
  push:
    branches: [ test ]

jobs:
  build_and_run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: SSH into remote server and build Docker image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ${{ secrets.TEST_SERVING_DIR }}
          git pull origin test
          docker build -t breed-classification-serving .
          docker run -d -p ${{ secrets.TEST_SERVING_DIR }}:${{ secrets.TEST_SERVING_DIR}} breed-classification-serving